settings:
  managers:
    brew:
      install: "brew install"
      remove: "brew remove"
      update: "brew upgrade"
    deb:
      install: "sudo nala install -y"
      remove: "sudo nala remove -y"
      update: "sudo nala update; sudo nala upgrade -y"
    flatpak:
      install: "flatpak install -y flathub"
      remove: "flatpak remove -y"
      update: "flatpak update -y"
    go:
      install: "go install"
      remove: "echo ''"

wares:
  wares:
    name: wares
    repo: indium114/wares
    asset: "wares_Linux_x86_64"
  hx:
    name: hx
    repo: helix-editor/helix
    asset: "*.AppImage"
  lazygit:
    name: lazygit
    repo: jesseduffield/lazygit
    asset: "lazygit_*_linux_x86_64.tar.gz"
  gh:
    name: bin/gh
    repo: cli/cli
    asset: "gh_*_linux_amd64.tar.gz"
    removetoplevel: true
  yazi:
    name: yazi
    repo: sxyazi/yazi
    asset: "yazi-x86_64-unknown-linux-musl.zip"
    removetoplevel: true
  libresprite:
    name: LibreSprite-x86_64.AppImage
    repo: libresprite/libresprite
    asset: "libresprite-development-linux-x86_64.zip"
  dotkeeper:
    name: dotkeeper
    repo: indium114/dotkeeper
    asset: "dotkeeper_Linux_x86_64"
  fastcards:
    name: fastcards
    repo: indium114/fastcards
    asset: "fastcards_Linux_x86_64"
  hocusfocus:
    name: hocusfocus
    repo: indium114/hocusfocus
    asset: "hocusfocus_Linux_x86_64"
  pricetag:
    name: pricetag
    repo: indium114/pricetag
    asset: "pricetag_Linux_x86_64"
  recall:
    name: recall
    repo: indium114/recall
    asset: "recall_Linux_x86_64"
  prismlauncher:
    name: prismlauncher
    repo: prismlauncher/prismlauncher
    asset: "PrismLauncher-Linux-x86_64.AppImage"
  tv:
    name: tv
    repo: alexpasmantier/television
    asset: "tv-*-x86_64-unknown-linux-musl.tar.gz"
    removetoplevel: true
  sheets:
    name: sheets
    repo: maaslalani/sheets
    asset: "sheets_Linux_x86_64.tar.gz"
  markdown-oxide:
    name: markdown-oxide
    repo: feel-ix-343/markdown-oxide
    asset: "markdown-oxide-v0.25.10-x86_64-unknown-linux-gnu"
  keepassxc:
    name: keepassxc
    repo: keepassxreboot/keepassxc
    asset: "KeePassXC-*-x86_64.AppImage"
  hx-fork:
    name: hx
    repo: gj1118/helix
    asset: "helix-linux-x86_64.tar.gz"
  nu:
    name: nu
    repo: nushell/nushell
    asset: "nu-*-x86_64-unknown-linux-musl.tar.gz"
    removetoplevel: true
    system: true
  helium:
    name: helium
    repo: imputnet/helium-linux
    asset: "helium-*-x86_64.AppImage"

blueprints:
  pkgit:
    repo: "https://git.symlinx.net/pkgit"
    steps:
      - "make"
    artifacts:
      - "pkgit"
  wares-git:
    repo: "https://github.com/indium114/wares"
    steps:
      - "nix develop --command go build"
      - "mv ./wares ./wares-git"
    artifacts:
      - "wares-git"
  termfarm:
    repo: "https://github.com/indium114/termfarm"
    steps:
      - "swift package reset"
      - "swift build --configuration release"
    artifacts:
      - ".build/release/termfarm"

managers:
  brew:
    - "fzf"
    - "fd"
    - "croc"
    - "gum"
    - "zoxide"
    - "eza"
    - "tlrc"
    - "delta"
    - "ncdu"
    - "luarocks"
    - "ripgrep"
    - "starship"
    - "btop"
    - "bat"
    - "fastfetch"
    - "ytsurf"
    - "typst"
    - "yamllint"
    - "tree-sitter-cli"
    - "television"
    - "pipes-sh"
    - "lua-language-server"
    - "pandoc"
    - "luacheck"
    - "just"
    - "glow"
    - "gopls"
    - "yamlfmt"
    - "jujutsu"
    - "aria2"
    - "forgejo-cli"
    - "swift"
  deb:
    - "figlet"
    - "tmux"
    - "libfuse2"
    - "pkg-config"
    - "nala"
    - "flatpak"
    - "libssl-dev"
    - "libxml2-dev"
    - "libcurl4-openssl-dev"
    - "zathura"
    - "zathura-pdf-poppler"
    - "zathura-djvu"
    - "vlc"
    - "libluajit-5.1-dev"
    - "liblua5.4-dev"
    - "libreoffice-writer"
    - "dino-im"
    - "gnuplot"
  go:
    - "github.com/indium114/theatre@latest"
    - "github.com/spf13/cobra-cli@latest"
    - "github.com/indium114/satchel@latest"
    - "github.com/indium114/jots@latest"
